### ISSUE TITLE
repository name

### ISSUE THREAD

**Issue by yalh76** [YunoHost-Apps/webtrees_ynh#7] opened 2019-04-18 03:14 UTC
I think that repository name should be all lower case as other apps: **w**ebtrees_ynh instead of ### Webtrees_ynh

**Comment by anmol26s** [comment] 2019-04-18 12:49
Made the name with lower case. Is this the cause for the CI failing?
Closing this as issue solution has been implemented but it would be good if someone can put light on the naming rules for the Yunohost packaging.

**Closed by anmol26s** 2019-04-18 12:49 UTC

**Comment by yalh76** [comment] 2019-04-18 13:04
I think, it’s not the reason the CI fails.
But as i’m trying to solve it. First step for me is to apply example_ynh and to be as close as possible of the standards ^^
